### ISSUE TITLE
Bound 'c' to something else, now it is unbound.

### ISSUE THREAD

**Issue by Mafwingo** [samuelmaddock/gm-mediaplayer#22]
I recently accidentally bound c to an act command and, upon realizing this didn't work with the media player, unbound it. Now I cannot use the media player at all anymore. I can only hit e to turn it on.  How do I rebind c to the media player?

**Comment by WinterPhoenix96** [comment]
Go to GMod's Options, and then under Keyboard, bind c to "Show Context Menu"

**Comment by Mafwingo** [comment]
Thank you so much.

**Comment by WinterPhoenix96** [comment]
No problem!
