### ISSUE TITLE
Media Player's Roboto fonts override the ones included with GMod

### ISSUE THREAD

**Issue by WinterPhoenix96** [samuelmaddock/gm-mediaplayer#23]
The ones included with the Workshop release at least, are overriding GMod's default Roboto fonts. They also exhibit various issues that the ones included with GMod do not.

Media Player:
![image](https://user-images.githubusercontent.com/2799393/43602639-88647b54-965e-11e8-9480-985d6dbc665b.png)

GMod:
![image](https://user-images.githubusercontent.com/2799393/43602732-d32cb55c-965e-11e8-98aa-178c0b694618.png)

pls fix sam

**Comment by WinterPhoenix96** [comment]
Fixed in https://github.com/samuelmaddock/gm-mediaplayer/commit/795209d4f283783913aa55f1f2e79ecbc98f880b . For anybody that sees this issue later on, it can be fixed by deleting the roboto .ttf files in ```
GarrysMod/garrysmod/cache/workshop/resource/fonts```

**Comment by Noiwex** [comment]
Gee no wonder everything in roboto looked like shit for some reason.
