### ISSUE TITLE
Request: Please merge image and direct file (and mouse cursor) support into Cinema Gamemode.

### ISSUE THREAD

**Issue by Xeddius** [samuelmaddock/gm-mediaplayer#32]
Exactly as the title states, it'd be wonderful to have these improvements put into Cinema. I've been really enjoying my private Cinema server between friends, but I haven't been able to load direct files from the web. I don't want to use just gm-mediaplayer because I really like the Cinema gamemode and we have a special map just for it. Plus, it's a pain to have everyone press E on the screen instead of everything loading automatically.

**Comment by catSIXe** [comment]
Contact me. steam: https://s.team/p/jbj-ppvc/fgkbtkhh

**Comment by WinterPhoenix** [comment]
This is the wrong repo for this, but the original Cinema gamemode is no longer being updated, nor does Sam still have access to it.

Try `cinema_toggle_controls` in console for a (intended for developers) mouse cursor.
