### ISSUE TITLE
Replace YouTube API with web scraping

### ISSUE THREAD

**Issue by samuelmaddock** [samuelmaddock/gm-mediaplayer#33]
> [Request Error] The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.

YouTube decided to kill this project's quota for some bogus reason today.

![image](https://user-images.githubusercontent.com/1656324/89323480-c1300200-d653-11ea-9453-ea726c99d468.png)

Instead of complying with API usage terms and getting harassed by Google's automation in the future, YouTube links should just be scraped for the necessary information.

In Metastream, I scrape the HTML instead of using their API (requires User-Agent header to use Googlebot value). Here's a reference implementation: https://github.com/samuelmaddock/metastream/blob/master/packages/metastream-app/src/media/middleware/youtube.ts

I don't have time to bother with implementing this in the Media Player addon. If anyone is interested in submitting a PR with the necessary changes, I'll take a look at merging and uploading it.

The YouTube service's `GetMetadata` function will need to be updated here: https://github.com/samuelmaddock/gm-mediaplayer/blob/master/lua/mediaplayer/services/youtube/init.lua

**Comment by WinterPhoenix** [comment]
Can it be effectively scraped serverside without upsetting some sort of rate limit or bot detection thing?

**Comment by samuelmaddock** [comment]
> 
> 
> Can it be effectively scraped serverside without upsetting some sort of rate limit or bot detection thing?

I haven't seen any problems related to rate limiting with web scraping YouTube. Scraping a single page is pretty common for social graph previews for getting [open graph tags.](https://ogp.me/)

**Comment by xXOCsonicLeEpicMemeXx** [comment]
I thought i was the only one with this issue, Well that sucks. Maybe its possible to add support for a different streaming service that streams videos from youtube?
